### ISSUE TITLE
Please provide feedback on a breaking change proposal.

### ISSUE THREAD

**Issue by matecsaj** [matecsaj/ebay_rest#15]
I'm considering changing ebay_rest.json as follows with the intention of:
- reducing the number of parameters needed when instantiating an API object
- providing the means to specify scope when required
- supporting use cases that have multiple application, user or header sets
- make terminology more intuitive
- make using .json optional, the alternative being to supply similar dicts when instantiating an API object
- make anticipated changes, like adding a new header or scope element, backwards compatible 

```
{
    "***_instructions_***": {
        "01": "The ebay_rest module needs your eBay credentials.",
        "02": "Copy this file to your working folder and name it ebay_rest.json.",
        "03": "As you create and get, replace the placeholders in the two sections that follow.",
        "04": "Create a developer account - https://developer.ebay.com/api-docs/static/creating-edp-account.html",
        "05": "Get your OAuth credentials - https://developer.ebay.com/api-docs/static/oauth-credentials.html",
        "06": "Get your redirect_uri value - https://developer.ebay.com/api-docs/static/oauth-redirect-uri.html",
        "07": "Create production and sandbox logins at your eBay country-specific marketplace, e.g. https://www.ebay.com & https://sandbox.ebay.com.",
        "08": "Except for production users, empty scopes will be auto-discovered.",
        "09": "If the token and token_expiry are empty, they will be auto-generated.",
        "10": "If using version control, keep your keys private by NOT checking in the file ebay_rest.json."
    },
    "applications": {
        "production_1": {
            "app_id": "example-example-PRD-example-example",
            "cert_id": "PRD-example-example-example-example-example",
            "dev_id": "example-example-example-example-example",
            "redirect_uri": "example-example-example-example",
            "scopes": [],
            "token": "",
            "token_expiry": ""
        },
        "sandbox_1": {
            "app_id": "example-example-SBX-example-example",
            "cert_id": "SBX-example-example-example-example-example",
            "dev_id": "example-example-example-example-example",
            "redirect_uri": "example-example-example-example",
            "scopes": [],
            "token": "",
            "token_expiry": ""
        }
    },
    "users": {
        "production_1": {
            "site": "https://www.ebay.com",
            "email_or_username": "<production-username>",
            "password": "<production-user-password>",
            "scopes": [
                "https://api.ebay.com/oauth/api_scope",
                "https://api.ebay.com/oauth/api_scope/sell.inventory",
                "https://api.ebay.com/oauth/api_scope/sell.marketing",
                "https://api.ebay.com/oauth/api_scope/sell.account",
                "https://api.ebay.com/oauth/api_scope/sell.fulfillment"
            ],
            "token": "",
            "token_expiry": ""
        },
        "sandbox_1": {
            "site": "https://sandbox.ebay.com",
            "email_or_username": "<sandbox-username>",
            "password": "<sandbox-user-password>",
            "scopes": [],
            "token": "",
            "token_expiry": ""
        }
    },
    "headers": {
        "ENCA": {
            "content_language": "en-US",
            "country" : "CA",
            "currency": "CAD",
            "marketplace_id": "EBAY_ENCA",
            "zip": "K1M 1M4"
        },
        "GB": {
            "content_language": "en-US",
            "country" : "GB",
            "currency": "GBP",
            "marketplace_id": "EBAY_GB",
            "zip": "SW1A 1AA"
        },
        "US": {
            "content_language": "en-US",
            "country": "US",
            "currency": "USD",
            "marketplace_id": "EBAY_US",
            "zip": "20500"
        }
    }
}
```

```
# API object creation parameters
class API:
    def __init__(self, application=None, user=None, header=None, throttle: bool = False, timeout: float = -1.0):

# when ebay_rest.json contains only one application, user and header record
api_one = API()

# when ebay_rest.json contains more than one application, user and header record
api_two = API(application='sandbox_1', user='sandbox_1', header='US')

# when a user credentials come from a database, and other credentials are loaded from ebay_rest.json
# pretend that the dict() contents are loaded from a database. 
user = dict(site="https://www.ebay.com", email_or_username="<production-username>",
            password="<production-user-password>", scopes=[
                "https://api.ebay.com/oauth/api_scope",
                "https://api.ebay.com/oauth/api_scope/sell.inventory",
                "https://api.ebay.com/oauth/api_scope/sell.marketing",
                "https://api.ebay.com/oauth/api_scope/sell.account",
                "https://api.ebay.com/oauth/api_scope/sell.fulfillment"
            ], token="", token_expiry="")
api_three = API(application='sandbox_1', user=user, header='US')
```

Some use cases do NOT need a user or header, so these will be optional. 

For developers that want to supply tokens, for the sake of consistency, should how that is done be reconsidered?

**Comment by gbm001** [comment]
Hi,

I don't use ebay_rest.json at all although I use the equivalent in ebaysdk for the TradingAPI. But all this seems reasonable?

You could add fields to give a user refresh token and expiry as an alternative to giving username/password (they last for 18 months) and then that provides an equivalent when passing details directly on API initialization.

**Comment by gbm001** [comment]
Could also be worth being able to supply a path to ebay_rest.json somewhere?

**Comment by matecsaj** [comment]
Your idea of providing either a user login or a token makes good sense because both are never needed.

Since the library can do an excellent job of getting and refreshing the application token, I suppose there is no point in making it possible to pass it in.

Having a sandbox True/False parameter makes it very clear whether sandbox or production is used. On the flip side, if production/sandbox can be inferred, having one less parameter to worry about makes things easier for the programmer. Undecided.

Yes, I suppose that a developer with a suite of programs might want them all to use the same ebay_rest.json file. For sure, I'll add a parameter for an optional path. I'm undecided if the file name should always be ebay_rest.json to help people find documentation about it or benefit from letting the programmer rename it.

I've got a prototype coded and will tweak it based on your helpful feedback. To make merging easier, I'll wait until the paging method changes finish.

**Comment by matecsaj** [comment]
A tweaked version of the proposal is complete and will be known as Beta version 8.

The changes will benefit someone:
- with multiple 'users'
- not wanting to use ebay_rest.json for credentials
- that must supply a 'user token'

To upgrade, in a terminal run
```
pip install ebay_rest -U
```

How an API object is instantiated has changed, so that:
1. record names in ebay_rest.json can be specified
2. dicts mimicking ebay_rest.json records can be supplied, making ebay_rest.json unnecessary
3. if there is only one set of records in ebay_rest.json that they will be automatically used
4. or a combination of all three

The sandbox parameter is no longer required; it is inferred from the credentials supplied. Here is some code for those who miss the sandbox parameter.

```
# Environment
SANDBOX = False  # change to True for PRODUCTION 
if SANDBOX:
    APPLICATION = 'sandbox_1'
    USER = 'sandbox_1'
else:
    APPLICATION = 'production_1'
    USER = 'production_1'
HEADER = 'ENCA'
```

api = API(application=APPLICATION, user=USER, header=HEADER, throttle=False)

The API method that loaded a user token is no longer necessary as the token now can be supplied during API instantiation.

Search for 'API(' in your python code and alter per the example in the [ReadMe.md](https://github.com/matecsaj/ebay_rest) and read API's __init__ docstring for more options.

Modify your ebay_rest.json file per [this](https://github.com/matecsaj/ebay_rest/blob/main/tests/ebay_rest_EXAMPLE.json).

Unfortunately, the enhancements triggered a new [issue](https://github.com/matecsaj/ebay_rest/issues/19).
