### ISSUE TITLE
Is there another method for getting user tokens?

### ISSUE THREAD

**Issue by matecsaj** [matecsaj/ebay_rest#17]
It is clunky to get a user token via eBay's online developer tools or a combination of chrome-webdriver-selenium. Do you know of a method that is more simple, reliable, speedy and unobtrusive?

**Comment by gbm001** [comment]
Everything I have read about eBay's user token flow strongly suggests it is indeed complicated, poorly-documented and clunky. I don't think there's much we can do about that, sadly...

**Comment by matecsaj** [comment]
I re-read eBay's developer documentation about OAuth with this topic in mind. eBay appears to have prioritized "consent" over "convenience." They made a wise choice, considering what is possible after the user grants consent.

I concur with gbm001 in that putting up with it is the only option, so I'm going to close this issue.
