### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by alefisico** [matecsaj/ebay_rest#24]
Hi 
I am very interested in using and contributing to your code in the future, but I am having some problems running the example in the "Usage" part of the README.md. 
I followed the instructions in `ebay_rest_EXAMPLE.json` and I changed these lines [1], but I am getting the following error:
```
eBay's official date and time is 2021-11-09T21:03:37.135Z.

All valid eBay global id values, also known as site ids.
[{'ebay_site_id': '16', 'global_id': 'EBAY-AT',.......

The five least expensive iPhone things now for sale on-eBay:
Error 1 is token_application.error 401: client authentication failed None.
``` 
Do you know what am I doing wrong? Thanks a lot for the help.

[1] https://github.com/matecsaj/ebay_rest/blob/main/tests/ebay_rest_EXAMPLE.json#L14-L24

**Comment by matecsaj** [comment]
If you provide a screenshot of your ebay_rest.json file I might be able to spot a cut-paste error. Security warning, protect your privacy by blurring your ids beyond recognition or blacking out portions of them. 

Things to try include: 

1. If you provide a screenshot of your ebay_rest.json file, I might be able to spot a cut-paste error. Security warning, protect your privacy by blurring your ids beyond recognition or blacking out portions of them. 

2. Repeat the copy paste of your credentials.

3. Debug the code. 

The first line of the following method in ebay_rest/src/ebay_rest/token.py would be a great place to debug breakpoint. 

    def _refresh_application(self):
        """ Refresh the eBay Application Token and update all that comes with it."""
        token_application = self._oauth2api_inst.get_application_token(self._application_scopes)
        if token_application.error is not None:
            reason = 'token_application.error ' + token_application.error
            raise Error(number=1, reason=reason)
        if (token_application.access_token is None) or (len(token_application.access_token) == 0):
            raise Error(number=1, reason='token_application.access_token is missing.')

When debugging, make the same call with the API Explorer tool and see if the credentials match up. The generated tokens will be different and can be cut and pasted.

**Comment by matecsaj** [comment]
Alefisico, please provide a status update.

**Comment by matecsaj** [comment]
The submitter appears to have lost interest in the issue.
