### ISSUE TITLE
type checking order

### ISSUE THREAD

**Issue by pseudomonas** [matecsaj/ebay_rest#27]
I'm getting errors caused by checking whether a term is present within data that is not a list or dict.

/api/buy_feed/api_client.py line 615

```
if (data is not None and
    klass.attribute_map[attr] in data and
    isinstance(data, (list, dict))
    ):

```
should (I think) be reordered to read: 

```
if (data is not None and
    isinstance(data, (list, dict)) and
    klass.attribute_map[attr] in data
    ):
```

which suppresses the error, though the module then fails to do anything with the bytestream that the buy.feed api returns.

**Comment by matecsaj** [comment]
Great to hear from you. Which buy_feed call and with what parameters? Please supply a snippet of code that triggers the problem.

**Comment by matecsaj** [comment]
Will you be supplying additional information, or should I close the issue?

**Comment by matecsaj** [comment]
This issue has gone cold. Lacking more information to work with, I'm closing the case.
