### ISSUE TITLE
Error 1 

### ISSUE THREAD

**Issue by eporto2021** [matecsaj/ebay_rest#29]
Hello,

I get the following message:

"Error 1 is Get configuration for application problem. The parameter application should not be a string or the configuration file should exist."

When I run the following code:

```
from ebay_rest import API, DateTime, Error, Reference

try:
    api = API(application='production_1',user='production_1',header="US")
except Error as error:
    print(f'Error {error.number} is {error.reason} {error.detail}\n')

```
Any idea why ?

**Comment by matecsaj** [comment]
Let me bring this [https://github.com/matecsaj/ebay_rest/blob/main/tests/ebay_rest_EXAMPLE.json](https://github.com/matecsaj/ebay_rest/blob/main/tests/ebay_rest_EXAMPLE.json) to your attention.

I'll reclassify this as a 'documentation issue' and improve the error message in the next monthly release.

**Comment by eporto2021** [comment]
I seemed to have got rid of the error. I had already filled out the ebay_rest_EXAMPL.json file, I had this json file in a different subfolder within the project directory - as soon as I put it in the same folder as the above code it worked.

**Comment by matecsaj** [comment]
Committed the following for the next release. 
https://github.com/matecsaj/ebay_rest/commit/e31c8fe7bd782a7124ded4333b2d5b06e672394f#diff-43f7054d8033985c9c867378b0024858d3e7460fccb206082bdd7a904a7fa143
