### ISSUE TITLE
Selenium can't get past eBay's captchas

### ISSUE THREAD

**Issue by eporto2021** [matecsaj/ebay_rest#30]
There are many functions within the API class contained within the  a_p_i.py file. Some of these functions use selenium and chrome driver, these functions seem to trigger captchas on eBay and certain functions are then not able to fulfil their purpose. Is there something I'm not appreciating here that would allow me to bypass the captchas ?

**Comment by matecsaj** [comment]
Some API calls require a user token. 

In the eBay Rest library, there is a file called token.py and part of its job is to do this https://developer.ebay.com/api-docs/static/oauth-client-credentials-grant.html.

With your debugger, in token.py,  you can put in a breakpoint where  _get_authorization_code is called and capture your refresh_token and your refresh_token_expiry. Put a copy of these in ebay_rest.json, and the browser pop-up will stop.

I'll add code to dump these values to the information log and expand the Read Me for the next monthly release.

**Comment by matecsaj** [comment]
Here is the new code. 
https://github.com/matecsaj/ebay_rest/commit/0bf880cbfa220ec87798b46f51a5cfc197081700
