### ISSUE TITLE
Two edge cases when getting a year+ user token.

### ISSUE THREAD

**Issue by matecsaj** [matecsaj/ebay_rest#34]
5-seconds isn't enough time for a human to complete the captcha. Wait on the first screen 20 seconds more.

The 'Agree' prompt doesn't always appear. Skip this step when the button is not present.

They were drawn from the experiences of Max from Australia.

**Comment by matecsaj** [comment]
[Make timing flexible; wait until pages render, and improve error handling.
](https://github.com/matecsaj/ebay_rest/commit/dd23236f39e05636eff222f99df1e3699ce47d4a)

I will close this issue upon the next release.

**Comment by TheGiolly** [comment]
I took a look at the code change. 
Please take also into consideration the 2FA autentication after submitting the password

**Comment by matecsaj** [comment]
When you write 2FA (two-factor authentication), do you refer to the photo selection Captcha that sometimes appears or something different? If the latter, please describe what it is and how to make it happen.

Note that this line, which will be in the next monthly release, does have an extra +30 seconds for completing the Captcha. 
WebDriverWait(browser, 10+30).until(lambda x: x.find_element_by_name('userid')).send_keys(self._user_id)

**Comment by TheGiolly** [comment]
The 2FA can be enabled in the eBay account security settings.
https://accounts.ebay.it/acctsec/security-center
You can choose either to receive a notification on your smartphone or to receive an SMS.

![2FA_webpage](https://user-images.githubusercontent.com/9699045/150178853-bcf76756-2d5b-4132-9e5e-39c7895aa1e7.png)
![2FA_notification](https://user-images.githubusercontent.com/9699045/150178984-c4561ddb-3306-4e16-894a-d56e991ecba8.png)

**Comment by matecsaj** [comment]
I get it now; thanks for explaining so clearly. I prefer not to have 2FA on my eBay account, and enabling may be irreversible. Would you kindly contribute a PR or, by some other means, communicate which timer needs to be longer?

If you don't remember, the method _get_authorization_code is in token.py.

**Comment by TheGiolly** [comment]
I already added a comment to the commit 4 days ago
https://github.com/matecsaj/ebay_rest/commit/dd23236f39e05636eff222f99df1e3699ce47d4a#r64040490

**Comment by matecsaj** [comment]
I see now, thanks. I did what you recommend; it will be in next month's release. Best wishes. https://github.com/matecsaj/ebay_rest/commit/1639569c6a344f8b08d26fc0e5da9ab929275452

**Comment by matecsaj** [comment]
I did the release early. To get it, run the following in your terminal/shell/command-line-window.

pip3 install ebay_rest -U
