### ISSUE TITLE
Only working on first "login"

### ISSUE THREAD

**Issue by TheGiolly** [matecsaj/ebay_rest#35]
Hi,
I just opened a market on my eBay account and now I cannot get ebay_rest to work properly.
I don't really know if the two thing are related or something else changed since I last used my software...
It worked flawlessly for months, but now it trows
`Error number96011. user_token.access_token is None. In ebay_rest.json, check refresh_token and refresh_token_expiry.`
when I, for example, call `sell_inventory_get_inventory_item`.

In token.py, I can see that the response from ebay is 
`b'{"error":"invalid_grant","error_description":"the provided authorization refresh token is invalid or was issued to another client"}'`
![Senza titolo](https://user-images.githubusercontent.com/9699045/153642901-0cb3c8a0-793b-4fa9-a6a6-6704d88b6097.png)

However, if I delete `refresh_token` and `refresh_token_expiry` from `ebay_reay.json` and I complete the login procedure through chromedriver it works. Then I close my software, save `refresh_token` and `refresh_token_expiry` in `ebay_reay.json` and it doesn't work.

Using ebay_rest 0.0.16, also tried 0.0.15 but nothing changed.

The API is working fine in the eBay's API Explorer

Edit: now it's not even letting me login.. in the chromedriver windows i get `{"error_id":"invalid_request","error_description":"Input request parameters are invalid.","http_status_code":400}`
(Fixed the edit by generating a new redirect URI, main problem still persists)

**Comment by TheGiolly** [comment]
Now it's working... Maybe something was updating in my eBay account after creating the market. Weird

**Comment by matecsaj** [comment]
It would appear that eBay had a temporary problem with their system.  Good to hear that the library works well for you most of the time.
