### ISSUE TITLE
Refactoring needed for token.py due to Selenium upgrade

### ISSUE THREAD

**Issue by albytterc** [matecsaj/ebay_rest#53]
Hi matecsaj,

I was using this library for a project I'm working on and I found there is now an error in token.py. Specifically, the _get_authorization_code() method which contains the x.find_element_by_name and x.find_element_by_id methods have been deprecated in Selenium 4.3.0. Anyone who'd like to do the user token flow now encounters NameErrors due to the deprecated methods.

Thanks,
Albert

**Comment by matecsaj** [comment]
Albert, thanks for the report. Please upgrade to version 0.0.21 and then retry.

`pip3 install ebay_rest -U`
