### ISSUE TITLE
get refresh token renew access token

### ISSUE THREAD

**Issue by eternalparquet** [matecsaj/ebay_rest#55]
Hello, is it possible to get a refresh token and renew the access token with this sdk?
If yes how to do that?

**Comment by matecsaj** [comment]
Greetings.

It is possible, [see](https://github.com/matecsaj/ebay_rest/issues/37).

An [enhancement](https://github.com/matecsaj/ebay_rest/issues/47) is planned to make direct use of token management more convenient; no timeline on that.
