### ISSUE TITLE
v0.31 pypi file differs from version in dist?

### ISSUE THREAD

**Issue by gbm001** [matecsaj/ebay_rest#72]
The file uploaded to pypi for v0.31 does not appear to have the encoding fixes for digital signatures, so I'm not getting those fixes through pip?

It does not appear to be the same as the file in the 'dist' directory for v0.31.

**Comment by matecsaj** [comment]
This morning I made a '32 version. Please upgrade and close. Let me know if all is well now.

**Comment by gbm001** [comment]
All seems to be good now with v0.32 thanks :)
