### ISSUE TITLE
Error: developer_key_management_create_signing_key() missing 1 required positional argument

### ISSUE THREAD

**Issue by andreinl** [matecsaj/ebay_rest#79]
As from the README, create an instance of API and ask for digital_signature_key:

    api = API(application='sandbox_1', user='sandbox_1', header='US', digital_signatures=True) 
    key = api.get_digital_signature_key(create_new=True)

Got an error:

    "developer_key_management_create_signing_key() missing 1 required positional argument: 'content_type'"

**Comment by matecsaj** [comment]
Hello Andrei, 

I will respond this week to your question. 

—
Peter JOHN Matecsa
***@***.***
+1 519.909.9041

62 Berkley Cr.
Simcoe, Ontario
N3Y 2K5
CANADA

**Comment by matecsaj** [comment]
In [this file](https://github.com/matecsaj/ebay_rest/blob/main/tests/ebay_rest.py), please have a look at class APISandboxDigitalSignatureTests which contains unit tests that I run before every release. Could you refactor that into the working code you need?

This portion of the library, including the documentation, was contributed by someone else, so my knowledge is limited. Would you like me to ask if he will help?

**Comment by andreinl** [comment]
The test is already there but it is skiped because of the way eBay works:

    # This test permanently creates a new public/private key pair which cannot
    # be removed, hence it is skipped by default.
    
   If you comment the skip line (Line 932) you will get the error.
   
   To create key pair I permanently added required argument to the function call. So the line 813 of the file token.py looks like this now:
   
    key = api.developer_key_management_create_signing_key(content_type='application/json', body=body)
    
I can make a pull request with this change if you like the solution

**Comment by matecsaj** [comment]
Thanks for finding a solution and offering to share; please submit a PR.

**Comment by andreinl** [comment]
I made a PR, but unittest will still fail because it also calls sell_finances_get_transaction_summary() which also requires new arguments ('x_ebay_c_marketplace_id')

**Comment by matecsaj** [comment]
Thanks again, Andre; today's release includes your fixes.
