### ISSUE TITLE
The method_paged is easy, but means you lose warnings.

### ISSUE THREAD

**Issue by gbm001** [matecsaj/ebay_rest#8]
The current system of returning a generator for some calls is both efficient and gloriously simple for building a list of items but makes it impossible to get, for example, warnings (I don't know if there's anything else of interest eBay supplies with paged calls). I'm not sure what the best way of dealing with this is; it could be, for example:

- A custom generator class which retains the warnings
- A function passed to the call via a keyword argument that accepts warnings
- Just be returning the full response with each iteration (to be dealt with by the client) which is the most flexible method. This could be turned on with a keyword argument to the call

Thoughts?

**Comment by gbm001** [comment]
Looking at something like buy_browse_search, it looks like there are various possible paged return fields you might want like autoCorrections other than just warnings, so it would be useful to collect these. Possibly these will be consistent across all the paged result so you can just retrieve them from the first call (maybe)?

**Comment by gbm001** [comment]
Alternative that maintains the current behaviour: #11

**Comment by matecsaj** [comment]
If the paging method threw an exception with all the error details, would that satisfy your needs?

**Comment by gbm001** [comment]
Well, not really - not all calls return warnings and I don't think routinely raising exceptions for warnings is reasonable. But more generally there are 'paged' calls where you want some of the other fields. There are also calls which return arrays (as lists) which are not the 'paged' field, which means the current scheme runs the risk of returning the 'wrong' field.

If there isn't some reasonably-straightforward way of getting the full pages then it's impossible to get the full eBay response for a large number of calls using this module. However, to preserve the existing behaviour by default I have proposed the other pull request where the default for the parameter record_list_key is 'auto' i.e. try and guess what the paged field is, and return that. You can then either pass the correct field, if the guess is incorrect, or pass None to get the full pages.

**Comment by matecsaj** [comment]
The library is still Beta; there will be no better time for breaking changes. One PR has 'alternative' in the title, so kindly advise on which subset you recommend merging.

**Comment by gbm001** [comment]
I think the simpler proposal is probably this one; your generator then returns full pages but if you pass a record_list_key (not record_key_list as I've written by accident somewhere) you get just the entries you want. Possibly it should just be 'record_key' for simplicity.

It will mean I have to fix up the documentation and the probably any paged tests though, but I can do that.

**Comment by gbm001** [comment]
I'm less familiar with the REST API, but one of the important warnings for me in the Trading API is the 'HardExpirationLimit' i.e. 'your token runs out in 10 days' or whatever (at which point I need to get a new token through the developer portal). That's not the sort of thing you want to raise an error for.

I like the idea of (limited) automatic retry for communication errors; the eBay API does quite often seem to give them so retrying up to three times per call seems very reasonable.

"I could not find any paged methods that don't use 'record_key' and would be interested to learn of any." - wasn't quite sure what you meant by this? I don't think 'record_key' is something in the eBay API but possibly I have missed something?

I'm not sure there's any good way of automatically working out which of the returned fields of a call is the paged field, at least not in a simple way. The advantage of requiring the caller to specify the paged field, or they get pages, means the default behaviour is well-defined (you get the pages) and if the caller wants the individual records, they can have them and they reliably get the right field (because they had to supply it). The disadvantage is obviously that it is slightly faffier and requires good documentation.

Your alternate solution does remove some complexity, and most of the time will give someone what they want straight away - they call 'get_items', they get items (which is definitely a Good Thing). However, the results won't be reliably the same - for some methods you will suddenly get paged data if there are warnings or other list data, which might also depend on what parameters you pass to the call (e.g. with the buy_browse search, you get items if you don't turn on autocorrect and you get the page_ attribute if you do).

Actually you could just *always* pass the page_ parameter, which might actually work quite well? (together with a page_i indicating which page is attached, maybe). But you'd still want identifying the paged field to be reliable. You could probably make it _fairly_ reliable by checking for a list with the right length, but that wouldn't be reliable when the 'right' length was small. Having thought about it, I quite like the 'page_' solution if only we could reliably get the 'right' field.

There may be some solution we haven't thought of yet! You could have a helper function that unpacks records, but that's probably more hassle. If you could reliably identify the paged field, you could create two API calls for each paged method e.g. sell_fulfillment_get_items and sell_fulfillment_get_items_pages or something, but that's just fragmenting the API.

**Comment by matecsaj** [comment]
It is comforting to know that we are not the ones wondering what the most pythonic way to convey a generator's ancillary information is; here are a couple of examples:
-[Handle an exception thrown in a generator]( https://stackoverflow.com/questions/11366064/handle-an-exception-thrown-in-a-generator)
-[Handle generator exceptions in its consumer](https://stackoverflow.com/questions/11366892/handle-generator-exceptions-in-its-consumer)

And, using logger is yet another option. 

Likely implementing any solution is better than leaving this issue hanging indefinitely, so I did what I felt would make the minor work for current and future library users. Code changes are [here](https://github.com/matecsaj/ebay_rest/commit/f96dd6eeb343e7fdafdd42535a696fba6ef369c6). Users will need to add three lines of code; search for the word 'record,' added to the [ReadMe](https://github.com/matecsaj/ebay_rest/blob/main/README.md).
