### ISSUE TITLE
Why not Playwright?

### ISSUE THREAD

**Issue by caner-cetin** [matecsaj/ebay_rest#82]
I see that https://github.com/matecsaj/ebay_rest/blob/main/src/ebay_rest/token.py#L409 in some places, we are waiting for the DOM to load, or to be stable. So why not just using Playwright? See: https://playwright.dev/python/docs/api/class-locator#locator-wait-for. This way you can actually get a timeout input from the user not just wait for X seconds or wait for a hardcoded seconds and timing out everything. Just an idea.

also syntax looks better, at least to me lol.

**Comment by matecsaj** [comment]
The month's release will have this. For changes see https://github.com/matecsaj/ebay_rest/commit/35c20f77e7a6f3e06e0ed5d36ec93d6c9875d569.
