### ISSUE TITLE
Unable to install via pip

### ISSUE THREAD

**Issue by aeorxc** [matecsaj/ebay_rest#83]
hi

when i try to install:
pip install ebay-rest
or 
pip install ebay_rest

It shows via pip list as:
Package            Version
------------------ -----------
ebay-rest          0.0.37

but then i can't import :
from ebay_rest import find

gives:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 1
----> 1 from ebay_rest import find

ModuleNotFoundError: No module named 'ebay_rest'

How can i fix this?

**Comment by matecsaj** [comment]
Four classes are available for import; please try this Python line.
```python
from ebay_rest import API, DateTime, Error, Reference
```

**Comment by matecsaj** [comment]
No further correspondence, so closing.
