### ISSUE TITLE
96015 Error upon running request

### ISSUE THREAD

**Issue by marley-achilles** [matecsaj/ebay_rest#86]
Hi team,

I'm getting a 96015 error "Element not found. Has eBay's website changed?" error whenever I run my code. I haven't been able to find any reference to this error within the ebay_rest documentation or eBay's own documentation and am at a bit of a loss on how to troubleshoot this. 

Looking at token.py, it seems to be an issue with generating an Auth token. My understanding is that a browser window is meant to pop up upon submitting a request, but this doesn't happen. I have confirmed that all provided credentials are correct and the redirect uri (seems to be what token.py is using to generate the token) matches the four-hyphen-separated string in my eBay Dev portal.

Could anyone provide any insight on how I would troubleshoot this issue here? Quite new to python, so any info would be greatly appreciated!

**Comment by marley-achilles** [comment]
That's working much better, thanks so much!

**Comment by matecsaj** [comment]
Your feedback is appreciated. The next release will include improved error reporting. https://github.com/matecsaj/ebay_rest/commit/23b75016a301a0af6c22f767e1f828ca8567b679
